# Numpy - Numerical Python
NumPy, büyük, çok boyutlu diziler ve matrisler üzerinde yüksek performanslı işlemler gerçekleştirmek için tasarlanmış kapsamlı bir matematik kütüphanesidir. Python' ın bilimsel hesaplamalarda temel kütüphanelerindendir. 

NumPy dizileri, Python'un yerleşik liste türlerine göre daha az yer kaplar ve daha hızlı işlemler gerçekleştirir. Bu avantajlar, NumPy'nin dizileri verimli bir şekilde saklama ve işleme yöntemlerine dayanır. İşte bu avantajların temel nedenleri:

* Homojen Veri Türü:
  
NumPy dizileri homojendir, yani tüm öğeler aynı veri türündendir. Bu, dizinin bellekte nasıl saklanacağını ve işleneceğini önceden bilmek için diziyi daha verimli bir şekilde yönetebilir anlamına gelir. Python listeleri ise heterojendir; yani, tek bir listede farklı veri türlerinden öğeler saklayabilirler. Bu verilerin işlenebilmesi için her bir veri il beraber verinin tipinin de ayrıca tutulması gerekmektedir. Bu da hafıza ve işlem kullanımını verimsiz hale getirir.

* Düşük Seviye Bellek Kullanımı:

NumPy, veri depolama ve işleme için optimize edilmiş düşük seviyeli programlama dilleri olan C ve Fortran'ı kullanır. Bu diller, bellek yönetiminde ve matematiksel işlemlerde yüksek verimlilik sağlar. Bu, NumPy dizilerinin Python listelerine göre çok daha verimli bir şekilde bellek kullanması ve işlemleri daha hızlı gerçekleştirmesi anlamına gelir.

* Vektörleştirilmiş İşlemler: 

NumPy, birden fazla veri öğesi üzerinde aynı anda işlemler gerçekleştirebilen vektörleştirilmiş işlemleri destekler. Bu, döngüler kullanmadan veri üzerinde toplu işlemler yapılmasına olanak tanır ve işlem hızını önemli ölçüde artırır. Vektörleştirilmiş işlemler, işlemlerin C seviyesinde optimize edilmiş kodlar kullanılarak yapılmasını sağlar, bu da Python döngülerine göre çok daha hızlıdır.

In [ ]:
# Küçük dizilerde Numpy dizileri daha fazla alan tutarken boyut büyüdükçe belleği daha verimli kullanmaya başlar.
import numpy as np
import sys

print("------------------------------")
uzunluk = 7
print("uzunluk =", uzunluk)

liste = [*range(uzunluk)]
demet = tuple(liste)
dizi = np.array(liste)

print("liste   :", sys.getsizeof(liste))
print("demet   :", sys.getsizeof(demet))
print("array   :", sys.getsizeof(dizi))

print("------------------------------")
uzunluk = 123554524
print("uzunluk =", uzunluk)

liste = [*range(uzunluk)]
demet = tuple(liste)
dizi = np.array(liste)

print("liste   :", sys.getsizeof(liste))
print("demet   :", sys.getsizeof(demet))
print("array   :", sys.getsizeof(dizi))




## ndarray (N-dimensional array)

Numpy kitiphanesinin çok boyutlu tek tip veri tutan temel liste yapısıdır. Pyton listeleri veya demetleri aracığı ile oluşturulabilirler. *numpy.array()* komutu ile (veya *np.array()*) oluşturulurlar.

### Oluşturma

In [ ]:
# List veya demet veri tipi ile oluştururlabilirler
import numpy as np

liste = [1, 2, 3, 4, 5]
demet = (1, 2, 3, 4, 5)
arr_list = np.array(liste)
arr_tuple = np.array(demet)

print("*******************************")
print("arr_list :", arr_list)
print("type:    :", type(arr_list))
print("*******************************")
print("arr_tuple:", arr_tuple)
print("type:    :", type(arr_tuple))
print("*******************************")

ndarray yapısı ile çok boyutlu diziler oluşturulabilir. Bu şekilde vektörler, matrisler ve daha yüksek boyutlu veri yapıları ile çalışmak için uygun hale gelir.

#### 0-D array
- Boyutsuz dizilerdir. 
- Tek bir değer tutarlar.
- Skaler olarak kullanılırlar.
- İşlemlerde sayı gibi kullanılabilirler.
- Array işlemleri sonucu ortaya çıkabilirler. (1x3 - 3x1 matris çarpımı gibi.)

In [ ]:
import numpy as np

scalar = np.array(21)
print(scalar)
print("Dizi boyutu:", scalar.ndim)

#### 1-D array

Tek boyutlu, standart Python içindeki listelere karşılık gelirler. Sayı, metin gibi farklı tipte veriler tutabilirler fakat sadece tek tip veri bulundurabilir.

In [ ]:
import numpy as np

# Tam sayılardan oluşan 1D dizi
array_int = np.array([1, None, 2, 3, 4, 5])

# Ondalıklı sayılardan oluşan 1D dizi
array_float = np.array([1.5, 2.5, 3.5, None])

# Boolean değerlerden oluşan 1D dizi
array_boolean = np.array([True, None, False, False])

# String değerlerden oluşan 1D dizi
array_str = np.array(["a", "b", "c", "d"])

print("array_int  :", array_int)
print("array_float:", array_float)
print("array_bool :", array_boolean)
print("array_str  :", array_str)


#### Çok boyutlu diziler

İki boyutlu dizilerdir ve matematikteki matrislere benzerler. Elemanları aynı uzunlukta 1D arraylardan oluşan dizidir.
Üç boyutlu diziler ise küp yapısındadır.

In [ ]:
import numpy as np
dizi2D = np.array([["00", "01", "02", "03"], ["10", "11", "12", "13"]])
print("dizi2D:")
print(dizi2D)
print("***************************")

dizi3D = np.array([[["000", "001", "002", "003"], ["010", "011", "012", "013"]],
                 [["100", "101", "102", "103"], ["110", "111", "112", "113"]]])
print("dizi3D:")
print(dizi3D)
print("***************************")

dizi4D = np.array([[[["0000", "0001", "0002", "0003"], ["0010", "0011", "0012", "0013"]],
                    [["0100", "0101", "0102", "0103"], ["0110", "0111", "0112", "0113"]]],

                 [[["1000", "1001", "1002", "1003"], ["1010", "1011", "1012", "1013"]],
                   [["1100", "1101", "1102", "1103"], ["1110", "1111", "1112", "1113"]]],

                 [[["2000", "2001", "2002", "2003"], ["010", "2011", "2012", "2013"]],
                   [["2100", "2101", "2102", "2103"], ["2110", "2111", "2112", "2113"]]]])
print("dizi4D:")
print(dizi4D)
print("***************************")

#### Özel yöntemler

In [ ]:
import numpy as np
zeros_array = np.zeros((3, 4))  # 3x4 boyutunda sıfırlarla dolu bir dizi oluşturur
ones_array = np.ones((2, 3))  # 2x3 boyutunda birlerle dolu bir dizi oluşturur
full_array = np.full((2, 2), 7)  # 2x2 boyutunda her elemanı 7 olan bir dizi oluşturur
identity_matrix = np.eye(4)  # 4x4 boyutunda bir birim matris oluşturur

print("********************")
print("np.zeros((3, 4))")
print(zeros_array)
print("********************")
print("np.ones((2, 3))")
print(ones_array)
print("********************")
print("np.full((2, 2), 7)")
print(full_array)
print("********************")
print("np.eye(4)")
print(identity_matrix)

Belirli aralıkta dizi oluşturma.

In [ ]:
import numpy as np
arange_array = np.arange(10)  # 0'ten (dahil) 10'a (hariç) kadar olan tam sayılar
arange_array_step = np.arange(start=5, stop= 20, step=4)  # 5'ten 20'ye kadar 4'er 4'er artan sayılar
linspace_array = np.linspace(0, 1, 5)  # 0 ile 1 arasında eşit aralıklı 5 sayı
random_array = np.random.random((3, 3))  # 3x3 boyutunda rastgele değerlerle dolu bir dizi oluşturur
normal_array = np.random.normal(0, 1, (3, 3))  # Ortalaması 0 ve standart sapması 1 olan normal dağılımlı rastgele değerler
int_random_array = np.random.randint(0, 10, (3, 3))  # 0 ile 10 arasında rastgele tam sayılarla dolu 3x3'lük bir dizi

print("********************")
print("np.arange(10)")
print(arange_array)
print("********************")
print("np.arange(0, 20, 2)")
print(arange_array_step)
print("********************")
print("np.linspace(0, 1, 5)")
print(linspace_array)
print("********************")
print("np.random.random((3, 3))")
print(random_array)
print("********************")
print("np.random.normal(0, 1, (3, 3))")
print(normal_array)
print("********************")
print("np.random.randint(0, 10, (3, 3))")
print(int_random_array)


### Eleman seçim

Temelde kullanım olarak Numpy dizileri ile standart Python listeleri oldukça benzerdir. Bazı kullanımlarda ek özellikler veya farklılıklar vardır.

In [ ]:
dizi = np.array([*range(15)])
print(dizi)
print("dizi[1]")
print(dizi[1])
print("dizi[2]")
print(dizi[2])
print("dizi[-2]")
print(dizi[-2])
print("dizi[1:2]")
print(dizi[1:2])

##### Soru:
dizi[1:2] ile dizi[1] arasında ne fark var?

In [ ]:
print("--------------------------")
print("dizi[1]:", dizi[1])
print(type(dizi[1])) 
# Int tipinde değer döndürdü.
# Bu da diziden tek bir eleman seçtiği anlamına gelir.
print("--------------------------")
print("dizi[1:2]", dizi[1:2])
print(type(dizi[1:2]))
# Sadece 1 elemanını içeren array tipinde veri döndürdü.
print("--------------------------")

In [ ]:
print("--------------------------")
print("dizi[1:10:2]")
print(dizi[1:10:2])

print("--------------------------")
print("dizi[5:]")
print(dizi[5:])

print("--------------------------")
print("dizi[:5]")
print(dizi[:5])

print("--------------------------")

In [ ]:
print("***************************")
print("dizi2D:")
print(dizi2D)
print("***************************")
print("dizi2D[1]:")
print(dizi2D[1])
print()
print("dizi2D[:,1]:")
print(dizi2D[:,1])
print()
print("dizi2D[0,1]:")
print(dizi2D[0,1])
print("***************************")



In [ ]:
print("***************************")
print("dizi3D:")
print(dizi3D)
print("***************************")
print("dizi3D[0]:")
print(dizi3D[0])
print()
print("dizi3D[0,1]:")
print(dizi3D[0,1])
print()
print("dizi3D[0,1,2]:")
print(dizi3D[0,1,2])
print()
print("dizi3D[:,:,1]:")
print(dizi3D[:,:,1])
print()
print("dizi3D[:,:,0:3]")
print(dizi3D[:,:,0:3])
print()
print("***************************")



In [ ]:
dizi = np.array([*range(720)])

dizi5D = dizi.reshape(2,3,4,5,6)

print(dizi5D[1,1,1,1])
print(dizi5D[1,1,1,1,2:5])

### Koşullu seçim

Numpy dizilerinde mantıksal seçim yapmak için, dizinin boyutuyla eşdeğer bir `True`-`False` (mantıksal) dizisi oluşturulabilir. Bu mantıksal dizi, orijinal dizinin elemanlarını seçmek veya atlamak için kullanılır. Mantıksal dizideki `True` değerlere karşılık gelen indeksler, orijinal diziden seçilirken `False` değere karşılık gelen indeksler atlanır..

In [ ]:
# Rastgele bir dizi oluşturduk.
dizi = np.random.randint(1,25,5)
print(dizi)

In [ ]:
# 0 ve 3 indeksleri atlanırken 1,2 ve 4 indeksleri seçilecektir.
mantıksal_dizi = [False, True, True, False, True]
print(dizi)
print(mantıksal_dizi)

dizi_secim = dizi[mantıksal_dizi]
print(dizi_secim)

In [ ]:
# Aşağıdaki komut bize mantıksal bir dizi döndürür.
# Dizimizin elemanlarını tek tek mantıksal sınamaya sokar ve bunlara  karşılık gelen değerleri bir diziye atar.
dizi > 12

In [ ]:
# `dizi > 12` ifadesi, dizideki her elemanın 12'den büyük olup olmadığını kontrol eder.
# Kontrol sonucu 12'den büyük indekslere True ve diğerlerine False değerler veren bir mantıksal dizi döndürür.
# Bu mantıksal diziyi `dizi[mantıksal_dizi]` şeklinde kullanarak, orijinal dizide 12'den büyük olan elemanları listeler.
dizi[dizi > 12]

## Veri Tipleri

Numpy kütüphanesinde boyutlarına göre sınıflandırılmış veri tipleri kullanılır. Bu şekilde bellek yönetimi daha verimli hale getirilebilir. 

Tam Sayılar:

- int8, int16, int32, int64: İşaretli tam sayılar için.
- uint8, uint16, uint32, uint64: İşaretsiz tam sayılar için.

Ondalıklı:
- float16, float32, float64, float128: Farklı hassasiyetlere sahip kayan nokta sayıları için.


Karmaşık Sayılar:
- complex64, complex128, complex256: Gerçek ve sanal bileşenleri olan sayılar için.

Boolean:
- bool_: Mantıksal True (Doğru) veya False (Yanlış) değerlerini saklamak için.

Stringler:
- str_ veya unicode

Zaman:

- datetime64: Tarih ve zaman bilgilerini saklamak için.
- timedelta64: İki tarih veya zaman arasındaki farkı saklamak için.

Aralarındaki farkları tamsayılar üzerinden inceleye4lim. `int8` veri tipi tamsayıları **8 bit** yani **1 byte** ile tutarken `int16` **16 bit** yani **2 byte** alanda tutar.

42 sayısını iki farklı türde binary olarak yazalım:

`int8`  : 00101010
`int16` : 00000000 00101010

Görüldüğü üzere 42 sayısı için  1 byte yetmektedir.Bu da **1 byte** ile tutulabilecek -128 ile +127 aralığındaki sayılar için  `int16`, `int32` veya `int64` kullanmanın fazladan alan harcamaya sebep olacağı anlamına gelir. Aşağıdaki örnekte tüm diziler aynı aralıkta sayılar tutarken bellekte kapladıkları alanlar farklıdır.

In [ ]:
import numpy as np
import sys
aralik = range(120)

# int8:  -128:127 aralığı 
# 8 bit,1 byte
dizi8 = np.array([*aralik],dtype= "int8") 

# int16: -32,768:32,767 aralığı 
# 16 bit, 2 byte
dizi16 = np.array([*aralik],dtype= "int16")

# int32: -2,147,483,648:2,147,483,647 aralığı
# 32 bit, 4 byte
dizi32 = np.array([*aralik],dtype= "int32")
# int64 -9,223,372,036,854,775,808:9,223,372,036,854,775,807 aralığı
# 64 bit, 8 byte
dizi64 = np.array([*aralik],dtype= "int64")

boyut8 = sys.getsizeof(dizi8)
boyut16 = sys.getsizeof(dizi16)
boyut32 = sys.getsizeof(dizi32)
boyut64 = sys.getsizeof(dizi64)

print("boyut8  :", boyut8)
print("boyut16 :", boyut16)
print("boyut32 :", boyut32)
print("boyut64 :", boyut64)



Eğer `int8` veri türüyle 127'den büyük bir sayı girilirse, bu sayı doğrudan temsil edilemeyeceği için bir taşma (overflow) meydana gelir. Bu durumda genellikle sayıların döngüsel olarak taşması söz konusu olur. Yani, veri türünün üst sınırı olan 127'den sonra alt sınır olan -128'den devam ederek tekrar ilerler.

In [46]:
import numpy as np

# int8 veri türünde bir numpy dizisi oluşturalım
arr = np.array([127], dtype=np.int8)

# Bu diziyi yazdıralım
print("Orijinal dizi:", arr)

# Diziye 1 ekleyelim (taşma olacak)
arr += 1

# Sonucu yazdıralım
print("Sonuç:", arr)


Orijinal dizi: [127]
Sonuç: [-128]


In [48]:
import numpy as np
import sys

liste = [0, 1, 126, 127, 128, 129, 130, 254, 255]
dizi8 = np.array(liste, dtype= "int8") 
print(dizi8)


[   0    1  126  127 -128 -127 -126   -2   -1]


C:\Users\ocesur\AppData\Local\Temp\ipykernel_18936\2175425366.py:5: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  dizi8 = np.array(liste, dtype= "int8")
C:\Users\ocesur\AppData\Local\Temp\ipykernel_18936\2175425366.py:5: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  dizi8 = np.array(liste, dtype= "int8")
C:\Users\ocesur\AppData\Local\Temp\ipykernel_18936\2175425366.py:5: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 130 to int8 will fail in the f

## Fonksiyon ve nitelikler

### shape - reshape()

- *dizi.shape* komutu dizimizin boyutlarını verir. 
- *dizi.reshape()* komutu diziyi yeniden boyutlandırmayı sağlar.

In [52]:
dizi1 = np.array([*range(15)], dtype="i8")
print("dizi1.shape:", dizi1.shape)

yenidizi1 = dizi1.reshape(5,3)
yenidizi2 = dizi1.reshape(3,5)
print("***********************************")
print("yenidizi1.shape:", yenidizi1.shape)
print("yenidizi")
print(yenidizi1)
print("***********************************")
print("yenidizi2.shape:", yenidizi2.shape)
print("yenidizi")
print(yenidizi2)

dizi1.shape: (15,)
***********************************
yenidizi1.shape: (5, 3)
yenidizi
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
***********************************
yenidizi2.shape: (3, 5)
yenidizi
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
dizi1.reshape(4,3)

### *copy()*

Python listelerinde *copy()* fonksiyonu ile aynı mantıkla çalışır.

In [65]:
dizi = np.array([1, 2, 3])
atanmis_dizi = dizi
kopyali_dizi = dizi.copy()

# Orijinal dizide yapılan değişiklik atanmış diziyi etkilerken copy() kullanılan diziyi etkilemez.
dizi[0] = 120
print("atanmis_dizi :", atanmis_dizi)
print("kopyali_dizi :", kopyali_dizi)

atanmis_dizi : [120   2   3]
kopyali_dizi : [1 2 3]


### *concatenate()*

Dizileri birleştirmek için kullanılır.

In [67]:
import numpy as np

# 1D diziler
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 1D dizileri birleştirme
c = np.concatenate((a, b))
print(c)  # [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [ ]:
# 2D diziler
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Satır bazında (eksen 0) birleştirme
c = np.concatenate((a, b), axis=0)
print(c)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Sütun bazında (eksen 1) birleştirme
d = np.concatenate((a, b), axis=1)
print(d)
# [[1 2 5 6]
#  [3 4 7 8]]


### *stack()*

In [ ]:
import numpy as np

dizi1 = np.array([1, 2, 3])
dizi2 = np.array([4, 5, 6])

# Yeni bir eksen boyunca (varsayılan olarak en dışta) dizileri birleştirir
dizi_stack = np.stack((dizi1, dizi2))
dizi_vstack = np.vstack((dizi1, dizi2))
dizi_hstack = np.hstack((dizi1, dizi2))
dizi_dstack = np.dstack((dizi1, dizi2))
print("***********************")
print("dizi_stack")
print(dizi_stack)
print("***********************")
print("dizi_vstack")
print(dizi_vstack)
print("***********************")
print("dizi_hstack")
print(dizi_hstack)
print("***********************")
print("dizi_dstack")
print(dizi_dstack)
